# Generated by Django 3.2.3 on 2021-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_updateorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
